apiVersion: projectcalico.org/v3
kind: PacketCapture
metadata:
  name: storefront-capture
  namespace: storefront
spec:
  selector: app == "frontend"
  filters:
    - protocol: TCP
      ports:
        - 80
