apiVersion: projectcalico.org/v3
kind: StagedGlobalNetworkPolicy
metadata:
  name: aws-nodes.controlplane
spec:
  tier: aws-nodes
  order: 100
  selector: (has(kubernetes-host)&&environment == "master")
  namespaceSelector: ''
  serviceAccountSelector: ''
  ingress:
    - action: Allow
      protocol: TCP
      source: {}
      destination:
        notPorts:
          - '443'
    - action: Deny
      protocol: TCP
      source: {}
      destination:
        ports:
          - '443'
    - action: Pass
      notProtocol: TCP
      source: {}
      destination: {}
  egress:
    - action: Allow
      protocol: TCP
      source: {}
      destination:
        notPorts:
          - '443'
    - action: Deny
      protocol: TCP
      source: {}
      destination:
        ports:
          - '443'
    - action: Pass
      notProtocol: TCP
      source: {}
      destination: {}
  doNotTrack: false
  applyOnForward: false
  preDNAT: false
  types:
    - Ingress
    - Egress
