apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: host-endpoints.etcd
spec:
  tier: host-endpoints
  order: 0
  selector: env == "etcd"
  namespaceSelector: ''
  serviceAccountSelector: ''
  ingress:
    - action: Allow
      source: {}
      destination: {}
  egress:
    - action: Allow
      source: {}
      destination: {}
  doNotTrack: false
  applyOnForward: false
  preDNAT: false
  types:
    - Ingress
    - Egress
